
create database Product_Performance_DB ;
use	 Product_Performance_DB ;

/* OBJECTIVE : To analyze product-level performance using SQL techniques such as window functions and CTEs, 
               focusing on ranking, growth trends, and performance variability across products. */




## Q1. Calculate total revenue generated by each product.

	select p.product_name,
		  round(sum(s.revenue),2) as Total
			 from sales  as s
			  inner join products as p
			   on s.product_id = p.product_id
				group by p.product_name 
				 order by sum(s.revenue) desc ;	


##Q2. Identify products whose total revenue is below the overall average revenue across all products.

with cte as (
select p.product_name, 
           sum(s.revenue) as Total
               from sales as s
                inner join products as p
                    on s.product_id = p.product_id
                      group by p.product_name)
				select product_name, 
                         round(Total,2) as Total_Revenue
                                 from cte
									where Total < (select avg(Total) from cte) ;
                                    
                                    
/*Q3 : Calculate the percentage contribution of each product to total revenue.*/								

 
select p.product_name,
         round(sum(s.revenue),2) as Total_sales,
                round(sum(s.revenue)*100/sum(sum(s.revenue))over(),2)
                           as  contribution_to_revenue_percentage
                      from sales as s 
                         inner join products as p
                           on s.product_id = p.product_id
				group by p.product_name 
			order by total_sales desc ;
            
                       

/*Q4 Which product earns the highest profit in each country? */

select * from (
			select st.country, p.product_name,
				round(sum(s.profit),2) as Total_profit,
                dense_rank() over (partition by st.country  order by sum(s.profit) desc) as rnk
                   from stores as st 
                       inner join sales as s
                               on st.store_id = s.store_id
						inner join products as p
								 on p.product_id = s.product_id
				group by st.country, p.product_name ) as high
	where rnk = 1;


/*Q5 : Find the top 3 products within each category based on total revenue.*/

	with product_sales as 
		(
		  select p.category, p.product_name,
		     round(sum(s.revenue),2) as total_revenue
				from sales as s
					inner join products as p
					  on s.product_id = p.product_id
		group by p.category, p.product_name ),
									
	rank_table as (
		   select category, product_name, total_revenue,
dense_rank() over (partition by category order by total_revenue desc) as Rnk
					from product_sales )
					
			select Category, Product_name,
					Total_revenue,Rnk     
						from rank_table
						  where  Rnk <= 3 ;           

/*Q6 : Which product categories peak in which months? */

with group_table as (
		select monthname(c.`date`) as Months,
				  p.category,
				   round(sum(s.revenue),2) as Total_revenue
					from calendar as c
					 inner join sales as s
							on c.`date` = s.order_date
					  inner join products as p
							on p.product_id = s.product_id 
				group by monthname(c.`date`) , p.category )
                
    select * from (            
				select months as Month, category,
						   Total_revenue,
					  dense_rank() over (partition by months order by Total_revenue desc) as rnk
						from group_table ) as rank_table 
		where rnk = 1;

                           
/*Q7 : Categorize products by revenue and analyze their quantity */

with revenue as (
			select p.product_name,
						   round(sum(s.revenue),2) as Total_sales,
						   sum(s.quantity) as Total_quantity
						from sales as s
							 inner join products as p
							  on s.product_id = p.product_id
                            group by p.product_name ),
Tiered_data as (
				select *,
					ntile(3) over (order by Total_sales desc) Tile
					from revenue )
                    
		select Product_name, 
                  Total_sales, Total_quantity,
			case 
				when tile = 1 then "High Value"
                when tile = 2 then "Mid Value"
                else "Low Value"
                    end Performance_tier
		  from Tiered_data 
               order by total_sales desc;
		













